vtk_module(vtkIOImage
  DEPENDS
    vtkCommonCore
    vtkCommonDataModel
    vtkCommonSystem
    vtkCommonMath
    vtkCommonMisc
    vtkCommonTransforms
    vtkIOCore
    vtkIOGeometry
    vtkzlib
    vtkjpeg
    vtkpng
    vtktiff
    vtkmetaio
    vtkoggtheora
    vtksys
    vtkUtilitiesDICOMParser
  DEFAULT ON)
