vtk_module(vtkRenderingCore
  GROUPS
    StandAlone
  DEPENDS
    vtkCommonDataModel
    vtkCommonExecutionModel
    vtkCommonMath
    vtkCommonMisc
    vtkCommonSystem
    vtkCommonTransforms
    vtkCommonComputationalGeometry
    vtkFiltersSources
    vtkFiltersGeneral
    vtkFiltersGeometry
    vtkFiltersExtraction
    vtkIOImage
    vtkIOXML
  TEST_DEPENDS
    vtkTestingCore
  )
