vtk_module(vtkGUISupportQt
  GROUPS
    Qt
  DEPENDS
    vtkCommonDataModel
    vtkCommonExecutionModel
    vtkRenderingOpenGL
    vtkInteractionStyle
    vtkImagingCore
  TEST_DEPENDS
    vtkTestingCore
  EXCLUDE_FROM_WRAPPING
  )
