vtk_module(vtkRenderingVolume
  DEPENDS
    vtkImagingCore
    vtkRenderingOpenGL
  TEST_DEPENDS
    vtkTestingCore
    vtkTestingRendering
    vtkRenderingText
    vtkImagingSources
    vtkImagingGeneral
  )
