vtk_module(vtkInteractionWidgets
  DEPENDS
    vtkRenderingAnnotation
    vtkRenderingFreeType
    vtkRenderingVolume
    vtkFiltersModeling
    vtkFiltersHybrid
    vtkImagingGeneral
    vtkInteractionStyle
  TEST_DEPENDS
    vtkTestingRendering
    vtkInteractionStyle
    vtkFiltersModeling
    vtkRenderingLOD
    vtkImagingStencil
  )
