vtk_module(vtkInteractionWidgets
  DEPENDS
    vtkRenderingAnnotation
    vtkRenderingText
    vtkRenderingVolume
    vtkFiltersModeling
    vtkFiltersHybrid
    vtkImagingGeneral
  TEST_DEPENDS
    vtkTestingRendering
    vtkInteractionStyle
    vtkFiltersModeling
    vtkRenderingLOD
    vtkImagingStencil
  )
