vtk_module(vtkFiltersHybrid
  DEPENDS
    vtkCommonDataModel
    vtkCommonExecutionModel
    vtkImagingSources
    vtkRenderingOpenGL
    vtkFiltersGeneral
  COMPILE_DEPENDS
    vtkUtilitiesEncodeString
  TEST_DEPENDS
    vtkImagingCore
    vtkTestingRendering
  )
