vtk_module(vtkIOExport
  DEPENDS
    vtkCommonCore
    vtkRenderingCore
    vtkRenderingFreeType
    vtkImagingCore
    vtkIOCore
    vtkgl2ps
  TEST_DEPENDS
    vtkTestingRendering
    vtkRenderingOpenGL
  )
