vtk_module(vtkInfovisLayout
  DEPENDS
    vtkCommonExecutionModel
    vtkImagingHybrid
    vtkFiltersModeling
    vtkInfovisCore
  TEST_DEPENDS
    vtkRenderingLabel
    vtkRenderingOpenGL
    vtkTestingRendering
    vtkIOInfovis
  )
