vtk_module(vtkInfovisCore
  DEPENDS
    vtkCommonCore
    vtkCommonDataModel
    vtkCommonSystem
    vtkFiltersCore
    vtkFiltersExtraction
  TEST_DEPENDS
    vtkInfovisLayout
    vtkRenderingOpenGL
    vtkTestingRendering
    vtkIOInfovis
  )
